### ISSUE TITLE
RGB-D images resolution

### ISSUE THREAD

**Issue by parodiniccolo** [OpenMask3D/openmask3d#14]
Hi, first of all thanks for the great work,
I've been running openmask3D on my own data collected from an iPad app and iOS lidar images are limited to 192x256.

The image and depth size in your scene example are both 640x480.

In my use case: 
Image: 1024x768
Depth: 256x192

I was just wondering if the image and depth size need to match.

**Comment by aycatakmaz** [comment]
Hi Niccolò, 

Sorry for our late reply. In the current version of our codebase, the image and depth sizes should match.

Best,
Ayca
