### ISSUE TITLE
novel/base split on original Table 3

### ISSUE THREAD

**Issue by ZheningHuang** [OpenMask3D/openmask3d#2]
Dear Author,

Thank you for the great work. In the original paper, Table 3, I wonder if you could share your detailed split of base class and novel class. It would be great if you could provide these details so that future work can compare with this equally. Thanks a lot for your help.

<img width="1115" alt="image" src="https://github.com/OpenMask3D/openmask3d/assets/65077830/e4a8411d-ca33-4379-af28-6a1db3143939">

Best regards,
Zhening

**Comment by aycatakmaz** [comment]
Dear Zhening,

I am attaching the list of "base" classes from our experiments. All remaining classes from ScanNet200 were classified as "novel" classes.

Best,
Ayca 

[base_classes_scannet200.txt](https://github.com/OpenMask3D/openmask3d/files/13328346/base_classes_scannet200.txt)
