### ISSUE TITLE
How to add custom text prompts for Open Vocabulary Instance Segmentation

### ISSUE THREAD

**Issue by sarosijbose** [OpenMask3D/openmask3d#23]
Hi, thanks for providing the code here. While going through the files, I couldn't find a place to explicitly mention custom prompts to segment out objects in the scene. Also, how can we visualize the outputs obtained in the output 'experiment' folder?

**Comment by elisabettafedele** [comment]
Dear Sarosij,

Thank you for your interest in our work! I suggest you take a look at [this](https://github.com/OpenMask3D/openmask3d/blob/main/openmask3d/visualization/viz_sim_score_export.py). You should be able to enter arbitrary textual queries and visualise the mask similarity scores on the point cloud.

Let us know if you have any further question.

Best,
Elisabetta
