### ISSUE TITLE
Replica Dataset

### ISSUE THREAD

**Issue by Davidyao99** [OpenMask3D/openmask3d#5]
Great project!

Could you give some guidance as to how you processed the replica dataset and how to run the evaluation for OpenMask3D on replica dataset?

Thank you so much ;)

**Comment by aycatakmaz** [comment]
We shared processed GT instances for Replica via email. We will also update the repo with Replica related data and code at a later point. 

**Note to other people interested in Replica evaluation who might check this issue at a later time:** Feel free to send us an email and we will share our data and instructions for Replica evaluation!
