### ISSUE TITLE
Regarding the performance of OpenMask3D

### ISSUE THREAD

**Issue by Wang-pengfei** [OpenMask3D/openmask3d#6]
Hi, I have noticed that there are significant differences in performance between the two versions of the paper on arXiv. Can you please let me know if you made any methodological adjustments?

**Comment by aycatakmaz** [comment]
Hi,

Thank you for your interest in our work! After our first arXiv version, we discovered an inconsistency between our implementation of the multi-scale image cropping algorithm and the formula we outlined in the paper. This affected the way we increased the scale of the image crops in multi-scale image cropping algorithm, which caused issues in certain scenarios. For our camera-ready version, we fixed this issue, and re-ran our experiments with the corrected multi-scale cropping implementation. The latest version of our arXiv paper corresponds to these results.

Hope this answers your question!

**Comment by Wang-pengfei** [comment]
Thank you for the clarification. I now understand the issue and appreciate your efforts to address it.
