### ISSUE TITLE
Errors when following the steps

### ISSUE THREAD

**Issue by hithqd** [OpenMask3D/openmask3d#9]
Hi, thanks for your excellent work. I follow the official steps. But when I run `bash run_openmask3d_single_scene.sh`, errors are:

/fuxi_team14/users/yingcaihe/openmask3d/openmask3d/class_agnostic_mask_computation/get_masks_single_scene.py:61: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="config_base_class_agn_masks_single_scene.yaml")
/fuxi_team14/users/yingcaihe/openmask3d/openmask3d/class_agnostic_mask_computation/get_masks_single_scene.py:82: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="config_base_class_agn_masks_single_scene.yaml")
/opt/conda/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config_base_class_agn_masks_single_scene.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/opt/conda/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'loss/set_criterion': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/conda/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'matcher/hungarian_matcher': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/conda/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'callbacks/callbacks_instance_segmentation': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/conda/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'trainer/trainer600': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/conda/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'scheduler/onecyclelr': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/conda/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'optimizer/adamw': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/conda/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'metrics/miou': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/conda/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'model/mask3d': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/conda/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'logging/full': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/conda/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'data/indoor': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/opt/conda/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[2023-12-27 16:49:45,151][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpd3n80twp
[2023-12-27 16:49:45,157][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpd3n80twp/_remote_module_non_scriptable.py
Error executing job with overrides: ['general.experiment_name=experiment', 'general.checkpoint=/fuxi_team14/users/yingcaihe/openmask3d/resources/scannet200_model.ckpt', 'general.train_mode=false', 'data.test_mode=test', 'model.num_queries=120', 'general.use_dbscan=true', 'general.dbscan_eps=0.95', 'general.save_visualizations=false', 'general.scene_path=/fuxi_team14/users/yingcaihe/openmask3d/resources/scene_example/scene_example.ply', 'general.mask_save_dir=/fuxi_team14/users/yingcaihe/openmask3d/output/2023-12-27-16-49-39-experiment']
Error in call to target 'models.mask3d.Mask3D':
InstantiationException('Cannot instantiate config of type Res16UNet34C.\nTop level config must be an OmegaConf DictConfig/ListConfig object,\na plain dict/list, or a Structured Config class or instance.')
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

How can I solve it?

**Comment by aycatakmaz** [comment]
Hi,

Thanks for your interest in our work!

This could be an issue due to the hydra package version.
Could you verify that you have hydra-core version 1.0.5? Otherwise please reinstall hydra with the following command:

`pip install hydra-core==1.0.5`

Let me know if that works!

Best,
Ayca

**Comment by hithqd** [comment]
Thank you. I  reinstall hydra with the following command:

pip install hydra-core==1.0.5

and I check the version:
<img width="1067" alt="image" src="https://github.com/OpenMask3D/openmask3d/assets/37433515/6ad96c75-e3e5-4712-8911-09204e6ee6c9">

but another error comes. It seems also related to hydra?

[INFO] Extracting class agnostic masks...
[2023-12-27 17:11:48,267][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpk_dlbf9e
[2023-12-27 17:11:48,268][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpk_dlbf9e/_remote_module_non_scriptable.py
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 544, in _locate
    import_module(mod)
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'datasets.utils.VoxelizeCollate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/hydra/utils.py", line 61, in call
    type_or_callable = _locate(cls)
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 546, in _locate
    raise ImportError(
ImportError: Encountered error: `No module named 'datasets.utils.VoxelizeCollate'` when loading module 'datasets.utils.VoxelizeCollate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/opt/conda/lib/python3.10/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "/fuxi_team14/users/yingcaihe/openmask3d/openmask3d/class_agnostic_mask_computation/get_masks_single_scene.py", line 84, in main
    get_class_agnostic_masks(cfg)
  File "/opt/conda/lib/python3.10/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/fuxi_team14/users/yingcaihe/openmask3d/openmask3d/class_agnostic_mask_computation/get_masks_single_scene.py", line 68, in get_class_agnostic_masks
    c_fn = hydra.utils.instantiate(cfg.data.test_collation) #(model.config.data.test_collation)
  File "/opt/conda/lib/python3.10/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'datasets.utils.VoxelizeCollate' : Encountered error: `No module named 'datasets.utils.VoxelizeCollate'` when loading module 'datasets.utils.VoxelizeCollate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fuxi_team14/users/yingcaihe/openmask3d/openmask3d/class_agnostic_mask_computation/get_masks_single_scene.py", line 87, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 267, in run_and_report
    print_exception(etype=None, value=ex, tb=final_tb)  # type: ignore
TypeError: print_exception() got an unexpected keyword argument 'etype'

**Comment by aycatakmaz** [comment]
It seems that hydra is unable to import the `datasets.utils.VoxelizeCollate` package, and we suspect that this is because Python cannot find the package to import. We used Python version 3.8.5 while developing our model and set package import paths based on that version of Python. From your error log, it seems that you are using Python 3.10, and there might be differences between how Python imports modules from repo subfolders. This might be the cause for the error.

As outlined in our [README.md](https://github.com/OpenMask3D/openmask3d/blob/main/README.md), we can only provide specific package versions and environment requirements for python==3.8.5. You can try to explore whether you are able to import `datasets.utils.VoxelizeCollate` from the main directory and the directory of the script from which hydra is initialized. If this doesn't work, we can recommend reinstalling everything with python=3.8.5.

**Comment by Y-cushion** [comment]
Hello author, I had a similar problem with Mr. hithqd when installing the environment, I read your comments and tried to change the hydra-core to version 1.0.5, but it later gave me the following error:

Installing collected packages: antlr4-python3-runtime, omegaconf, hydra-core
  Attempting uninstall: antlr4-python3-runtime
    Found existing installation: antlr4-python3-runtime 4.9.3
    Uninstalling antlr4-python3-runtime-4.9.3:
      Successfully uninstalled antlr4-python3-runtime-4.9.3
  Attempting uninstall: omegaconf
    Found existing installation: omegaconf 2.3.0
    Uninstalling omegaconf-2.3.0:
      Successfully uninstalled omegaconf-2.3.0
  Attempting uninstall: hydra-core
    Found existing installation: hydra-core 1.3.2
    Uninstalling hydra-core-1.3.2:
      Successfully uninstalled hydra-core-1.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
detectron2 0.6 requires hydra-core>=1.1, but you have hydra-core 1.0.5 which is incompatible.
detectron2 0.6 requires omegaconf>=2.1, but you have omegaconf 2.0.6 which is incompatible.
Successfully installed antlr4-python3-runtime-4.8 hydra-core-1.0.5 omegaconf-2.0.6


I searched online and found that the hydra-core==1.0.5 version and detector2==0.4 version are corresponding, but the CUDA version and Pytorch version of detectron2 ==0.4 version are different from the environment, I would like to ask if you have similar situations before? Or is there any good advice you can give me about this situation, looking forward to your reply
